<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Zlink.Framework.AspNetCore" Version="0.25.0" />
    <PackageVersion Include="Zlink.Framework.Locations.Redis" Version="0.25.0" />
    <PackageVersion Include="Zlink.Stream.Connector" Version="0.25.0" />
  </ItemGroup>
</Project>
